### ISSUE TITLE
1.3版本适配

### ISSUE THREAD

**Issue by WayneWong97** [JunNanLYS/AutoStarRail#34]
1.3版本更新后锄大地自动第一场战斗结束后无法继续运行；
除停止功能外，模拟宇宙能否添加自动x次后停止参数。

**Comment by zjnGitHub** [comment]
关于锄大地：
目前我的精力放在世界自动寻路上，暂时无暇顾及模拟按键的锄大地，可以等一段时间后的自动寻路或者魔改模拟按键那一块(StarRailAssistant)，模拟按键作者已经停止维护和更新了。

关于模拟宇宙计数功能：
目前模拟宇宙是达到34次后结束，有时间我可以加上自动x次停止

**Comment by WayneWong97** [comment]
好的，谢谢。
如果模拟宇宙达到34次后结束，似乎自动x次停止的功能也没有太大用处。
期待您的后续更新。

**Comment by kz-wind** [comment]
模拟宇宙部分原项目已经5.30版本，锄大地部分可以用ASR1.73版本，都是随版本刚更新的，作者有考虑合并接入吗

**Comment by zjnGitHub** [comment]
锄大地模拟按键版现在只有集成版本可以使用，并且部分地图无法正常运行。

模拟宇宙在5.30版本将在下一个merge中
