### ISSUE TITLE
进入了界面，一运行就出现ModuleNotFoundError:求教呀，谢谢

### ISSUE THREAD

**Issue by EuterNoe** [JunNanLYS/AutoStarRail#40]
Traceback (most recent call last):
  File "c:\Users\EuterNoe\Downloads\Compressed\AutoStarRail-main\main.py", line 68, in __on_run_interface_button_clicked_slot
    method, err = self.text_to_method(text)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\EuterNoe\Downloads\Compressed\AutoStarRail-main\main.py", line 48, in text_to_method
    from script.stamina.main import Stamina
ModuleNotFoundError: No module named 'script.stamina.main'; 'script.stamina' is not a package

**Comment by EuterNoe** [comment]
出现了

**Comment by EuterNoe** [comment]
> gui界面出现没？

出现了

**Comment by EuterNoe** [comment]
网上搜了说是什么自建模块路径不对，搞了一晚上没搞明白

**Comment by JunNanLYS** [comment]
给出截图，日志，使用什么打开的cmd，shell还是IDE

**Comment by EuterNoe** [comment]
来了，大佬 ，用的cmd，日志没反应，只知道这些了，完全没搞明白。
![cmd](https://github.com/JunNanLYS/AutoStarRail/assets/106658327/c483b7b1-e2ce-40a9-93bc-ce730786dc93)
![日志](https://github.com/JunNanLYS/AutoStarRail/assets/106658327/e5c5797c-8e23-421f-982e-ff10cc8756e2)
](url)

**Comment by Mrtangji** [comment]
需要自己去把Auto_Simulated_Universe的代码打包下载放在对应的文件夹里才有模拟世界的模组

**Comment by EuterNoe** [comment]
> 需要自己去把Auto_Simulated_Universe的代码打包下载放在对应的文件夹里才有模拟世界的模组

不只是模拟世界，体力也刷不了

**Comment by JunNanLYS** [comment]
暂时无法复现你这个问题

**Comment by JunNanLYS** [comment]
模拟宇宙目前需要到Auto_Simulated_Universe拉取代码与原文件夹替换，后面新版本会直接放到压缩包中

**Comment by Mrtangji** [comment]
什么时候开放锄大地测试啊，目前用的别的脚本好像不是很完美，会卡进度。

**Comment by EuterNoe** [comment]
> 暂时无法复现你这个问题

好的，谢谢大佬，我再试试其他的
