### ISSUE TITLE
无法启动，好像缺少什么

### ISSUE THREAD

**Issue by AjiuQUQ** [JunNanLYS/AutoStarRail#46]
安装完依赖后启动，提示
![image](https://github.com/JunNanLYS/AutoStarRail/assets/136694970/7eb9e689-f7d8-470d-8fe1-039a52d3344c)
无法启动，gui界面也没有。

**Comment by JunNanLYS** [comment]
**没有遇到过这种问题，根据gpt给出回答：**
你遇到的问题可能是因为你的Qt应用程序无法找到所需的Windows平台插件。这可能是因为Qt的安装不完整，或者Windows平台插件没有被正确地放置在预期的目录中。

以下是一些可能的解决方案：

检查你的Qt安装是否包含Windows平台插件。在Qt的安装目录下，你应该能找到一个名为"plugins"的目录。在这个目录下，应该有一个名为"platforms"的子目录，其中应该包含一个名为"qwindows.dll"的文件。如果没有这个文件，你可能需要重新安装Qt或手动下载并放置这个文件。

**提醒一下，路径中不要有中文路径，我在readme中也有写到**

**Comment by JunNanLYS** [comment]
GPT给出的回答可能有问题，需要你去网上搜相关问题
